const { program } = require('commander');
import CommandBus from "../../application/CommandBus";
import Application from "../../application/Application";
import {login,createUser} from "./commands/User";
const application=new Application(new CommandBus());
application.start();
const console=program;
console.addCommand(login(application));
console.addCommand(createUser(application));
console.parse();
